# backend/services/batch_registry.py
"""배치 레지스트리 — 현황 허브가 노출하는 19개 배치의 정적 메타데이터.

job_id는 스케줄러 잡 id 및 services.job_runs.record 호출 id와 반드시 일치한다.
consensus는 자체 스케줄러 잡이 없고(daily_report_kr/us에 내장) next_run이 null이다.
일일 리포트는 시장별로 daily_report_kr(20:30 KST)·daily_report_us(07:00 KST) 2배치로 분리된다.
실적·월간 지표도 시장별로 분리: earnings_kr(KR Top2)/earnings_us(M7),
monthly_kr(KR수출)/monthly_us(FRED 경제지표).
각 배치는 market 속성(KR/US/공통)을 가진다 — 출처국 기준 분류(ADR-0013).
"""
from __future__ import annotations

BATCHES = [
    {
        "id": "daily_report_kr",
        "label": "일일 리포트 생성(국내)",
        "category": "report",
        "schedule_desc": "설정에 따름",
        "usage": ["리포트 탭"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": None,
        "scheduler_job_id": "daily_report_kr",
        "timezone": "Asia/Seoul",
        "misfire_grace_time": 82800,
        "market": "KR",
        "default_schedule": {
            "enabled": False,
            "type": "weekly",
            "days": ["mon", "tue", "wed", "thu", "fri"],
            "time": "20:30",
        },
    },
    {
        "id": "daily_report_us",
        "label": "일일 리포트 생성(해외)",
        "category": "report",
        "schedule_desc": "설정에 따름",
        "usage": ["리포트 탭"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": None,
        "scheduler_job_id": "daily_report_us",
        "timezone": "Asia/Seoul",
        "misfire_grace_time": 82800,
        "market": "US",
        "default_schedule": {
            "enabled": False,
            "type": "weekly",
            "days": ["mon", "tue", "wed", "thu", "fri"],
            "time": "07:00",
        },
    },
    {
        "id": "consensus",
        "label": "컨센서스 수집",
        "category": "report",
        "schedule_desc": "리포트 생성에 포함",
        "usage": ["리포트 컨센서스 차트", "목표가·의견수(상세·목록·대시보드)"],
        "editable": False,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/consensus/batch",
        "scheduler_job_id": None,
        "market": "공통",
    },
    {
        "id": "daily_digest",
        "label": "일일 다이제스트",
        "category": "report",
        "schedule_desc": "매일 08:00",
        "usage": ["다이제스트", "텔레그램"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/digest/generate-all",
        "scheduler_job_id": "daily_digest",
        "timezone": "Asia/Seoul",
        "market": "공통",
        "default_schedule": {"enabled": True, "type": "daily", "time": "08:00"},
    },
    {
        "id": "backlog_fetch",
        "label": "수주잔고 수집",
        "category": "report",
        "schedule_desc": "매주 일 04:00",
        "usage": ["리포트 상세(수주잔고)"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/report/backlog/refresh-all",
        "scheduler_job_id": "backlog_fetch",
        "timezone": "Asia/Seoul",
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "weekly", "days": ["sun"], "time": "04:00"},
    },
    {
        "id": "dividend_fetch",
        "label": "배당 수집",
        "category": "report",
        "schedule_desc": "매주 일 05:00",
        "usage": ["대시보드(배당수익률·연 예상배당)"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/stocks/dividends/refresh",
        "scheduler_job_id": "dividend_fetch",
        "timezone": "Asia/Seoul",
        "market": "공통",
        "default_schedule": {"enabled": True, "type": "weekly", "days": ["sun"], "time": "05:00"},
    },
    {
        "id": "disclosure_fetch",
        "label": "공시 피드 수집",
        "category": "report",
        "schedule_desc": "매일 07:30",
        "usage": ["리포트 상세(최신 공시)", "다이제스트"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/report/disclosures/refresh",
        "scheduler_job_id": "disclosure_fetch",
        "timezone": "Asia/Seoul",
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "daily", "time": "07:30"},
    },
    {
        "id": "earnings_kr",
        "label": "실적 갱신(국내)",
        "category": "market",
        "schedule_desc": "매주 일 03:00",
        "usage": ["Market Hub KR Top2"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/market/refresh-earnings?market=KR",
        "scheduler_job_id": "earnings_kr",
        "timezone": "Asia/Seoul",
        "misfire_grace_time": None,
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "weekly", "days": ["sun"], "time": "03:00"},
    },
    {
        "id": "earnings_us",
        "label": "실적 갱신(해외)",
        "category": "market",
        "schedule_desc": "매주 일 03:00",
        "usage": ["Market Hub M7"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/market/refresh-earnings?market=US",
        "scheduler_job_id": "earnings_us",
        "timezone": "Asia/Seoul",
        "misfire_grace_time": None,
        "market": "US",
        "default_schedule": {"enabled": True, "type": "weekly", "days": ["sun"], "time": "03:00"},
    },
    {
        "id": "monthly_kr",
        "label": "월간 지표(국내)",
        "category": "market",
        "schedule_desc": "매월 1일 02:00",
        "usage": ["Market Hub KR 수출"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/market/refresh-monthly?market=KR",
        "scheduler_job_id": "monthly_kr",
        "timezone": "Asia/Seoul",
        "misfire_grace_time": None,
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "monthly", "day_of_month": 1, "time": "02:00"},
    },
    {
        "id": "monthly_us",
        "label": "월간 지표(해외)",
        "category": "market",
        "schedule_desc": "매월 1일 02:00",
        "usage": ["Market Hub 경제지표"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/market/refresh-monthly?market=US",
        "scheduler_job_id": "monthly_us",
        "timezone": "Asia/Seoul",
        "misfire_grace_time": None,
        "market": "US",
        "default_schedule": {"enabled": True, "type": "monthly", "day_of_month": 1, "time": "02:00"},
    },
    {
        "id": "leverage_fetch",
        "label": "신용/반대매매 수집",
        "category": "market",
        "schedule_desc": "매일 07:00",
        "usage": ["수급지표(신용/반대매매)"],
        "editable": True,
        "trigger_kinds": ["auto"],
        "manual_endpoint": None,
        "scheduler_job_id": "leverage_fetch",
        "timezone": "Asia/Seoul",
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "daily", "time": "07:00"},
    },
    {
        "id": "lending_fetch",
        "label": "대차잔고 수집",
        "category": "market",
        "schedule_desc": "매월 5일 08:00",
        "usage": ["수급지표(대차잔고)"],
        "editable": True,
        "trigger_kinds": ["auto"],
        "manual_endpoint": None,
        "scheduler_job_id": "lending_fetch",
        "timezone": "Asia/Seoul",
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "monthly", "day_of_month": 5, "time": "08:00"},
    },
    {
        "id": "kr_rankings_fetch",
        "label": "KR 랭킹 수집",
        "category": "market",
        "schedule_desc": "장중 09–15시 10분마다",
        "usage": ["랭킹 탭(KR)"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/rankings/refresh?market=KR",
        "scheduler_job_id": "kr_rankings_fetch",
        "timezone": "Asia/Seoul",
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "interval", "every_minutes": 10, "start_hour": 9, "end_hour": 15},
    },
    {
        "id": "us_rankings_fetch",
        "label": "US 랭킹 수집",
        "category": "market",
        "schedule_desc": "장중 09–16시(NY) 10분마다",
        "usage": ["랭킹 탭(US)"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/rankings/refresh?market=US",
        "scheduler_job_id": "us_rankings_fetch",
        "timezone": "America/New_York",
        "market": "US",
        "default_schedule": {"enabled": True, "type": "interval", "every_minutes": 10, "start_hour": 9, "end_hour": 16},
    },
    {
        "id": "investor_trend_fetch",
        "label": "수급 추이 수집",
        "category": "market",
        "schedule_desc": "매일 18:00",
        "usage": ["랭킹 수급", "리포트 상세"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/investor/refresh",
        "scheduler_job_id": "investor_trend_fetch",
        "timezone": "Asia/Seoul",
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "daily", "time": "18:00"},
    },
    {
        "id": "short_sell_fetch",
        "label": "공매도 추이 수집",
        "category": "market",
        "schedule_desc": "매일 18:30",
        "usage": ["리포트 상세(공매도)"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/short-sell/refresh",
        "scheduler_job_id": "short_sell_fetch",
        "timezone": "Asia/Seoul",
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "daily", "time": "18:30"},
    },
    {
        "id": "kr_sector_fetch",
        "label": "KR 업종 모멘텀 수집",
        "category": "market",
        "schedule_desc": "매일 16:00",
        "usage": ["분석 섹터 모멘텀(KR)"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/analysis/sector/refresh-kr",
        "scheduler_job_id": "kr_sector_fetch",
        "timezone": "Asia/Seoul",
        "market": "KR",
        "default_schedule": {"enabled": True, "type": "daily", "time": "16:00"},
    },
    {
        "id": "guru_crawl",
        "label": "구루 크롤링",
        "category": "guru",
        "schedule_desc": "설정에 따름",
        "usage": ["Guru 페이지"],
        "editable": True,
        "trigger_kinds": ["auto"],
        "manual_endpoint": None,
        "scheduler_job_id": "guru_crawl",
        "timezone": "Asia/Seoul",
        "market": "공통",
        "default_schedule": {"enabled": False, "type": "weekly", "days": ["sun"], "time": "03:00"},
    },
]

_BY_ID = {b["id"]: b for b in BATCHES}


def get_batch(job_id: str) -> dict | None:
    """job_id로 배치 레지스트리 항목 조회(없으면 None)."""
    return _BY_ID.get(job_id)
