# backend/services/batch_registry.py
"""배치 레지스트리 — 현황 허브가 노출하는 11개 배치의 정적 메타데이터.

job_id는 스케줄러 잡 id 및 services.job_runs.record 호출 id와 반드시 일치한다.
consensus는 자체 스케줄러 잡이 없고(daily_report에 내장) next_run이 null이다.
"""
from __future__ import annotations

BATCHES = [
    {
        "id": "daily_report",
        "label": "일일 리포트 생성",
        "category": "report",
        "schedule_desc": "설정에 따름",
        "usage": ["리포트 탭"],
        "editable": True,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": None,
        "scheduler_job_id": "daily_report",
    },
    {
        "id": "consensus",
        "label": "컨센서스 수집",
        "category": "report",
        "schedule_desc": "리포트 생성에 포함",
        "usage": ["리포트 컨센서스 차트"],
        "editable": False,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/consensus/batch",
        "scheduler_job_id": None,
    },
    {
        "id": "daily_digest",
        "label": "일일 다이제스트",
        "category": "report",
        "schedule_desc": "매일 08:00",
        "usage": ["다이제스트", "텔레그램"],
        "editable": False,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/digest/generate-all",
        "scheduler_job_id": "daily_digest",
    },
    {
        "id": "earnings_refresh",
        "label": "실적 갱신",
        "category": "market",
        "schedule_desc": "매주 일 03:00",
        "usage": ["Market Hub M7/KR Top2"],
        "editable": False,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/market-indicators/refresh-earnings",
        "scheduler_job_id": "earnings_refresh",
    },
    {
        "id": "monthly_refresh",
        "label": "월간 지표 갱신",
        "category": "market",
        "schedule_desc": "매월 1일 02:00",
        "usage": ["Market Hub 경제지표", "KR 수출"],
        "editable": False,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/market-indicators/refresh-monthly",
        "scheduler_job_id": "monthly_refresh",
    },
    {
        "id": "leverage_fetch",
        "label": "신용/반대매매 수집",
        "category": "market",
        "schedule_desc": "매일 07:00",
        "usage": ["수급지표(신용/반대매매)"],
        "editable": False,
        "trigger_kinds": ["auto"],
        "manual_endpoint": None,
        "scheduler_job_id": "leverage_fetch",
    },
    {
        "id": "lending_fetch",
        "label": "대차잔고 수집",
        "category": "market",
        "schedule_desc": "매월 5일 08:00",
        "usage": ["수급지표(대차잔고)"],
        "editable": False,
        "trigger_kinds": ["auto"],
        "manual_endpoint": None,
        "scheduler_job_id": "lending_fetch",
    },
    {
        "id": "kr_rankings_fetch",
        "label": "KR 랭킹 수집",
        "category": "market",
        "schedule_desc": "장중 09–15시 10분마다",
        "usage": ["랭킹 탭(KR)"],
        "editable": False,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/rankings/refresh?market=KR",
        "scheduler_job_id": "kr_rankings_fetch",
    },
    {
        "id": "us_rankings_fetch",
        "label": "US 랭킹 수집",
        "category": "market",
        "schedule_desc": "장중 09–16시(NY) 10분마다",
        "usage": ["랭킹 탭(US)"],
        "editable": False,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/rankings/refresh?market=US",
        "scheduler_job_id": "us_rankings_fetch",
    },
    {
        "id": "investor_trend_fetch",
        "label": "수급 추이 수집",
        "category": "market",
        "schedule_desc": "매일 18:00",
        "usage": ["랭킹 수급", "리포트 상세"],
        "editable": False,
        "trigger_kinds": ["auto", "manual"],
        "manual_endpoint": "/api/investor/refresh",
        "scheduler_job_id": "investor_trend_fetch",
    },
    {
        "id": "guru_crawl",
        "label": "구루 크롤링",
        "category": "guru",
        "schedule_desc": "설정에 따름",
        "usage": ["Guru 페이지"],
        "editable": True,
        "trigger_kinds": ["auto"],
        "manual_endpoint": None,
        "scheduler_job_id": "guru_crawl",
    },
]
